apiVersion: skaffold/v2beta26
kind: Config

build:
  local:
    push: false
  artifacts:
    - image: leijun/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: leijun/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*